
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rikiel
 */
public class main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(main.class.getName());

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registerbutton = new javax.swing.JButton();
        adminbuttton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("School Enrollment System");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school logo1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(535, 535, 535)
                .addComponent(jLabel1)
                .addContainerGap(649, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 120);

        registerbutton.setBackground(new java.awt.Color(153, 255, 153));
        registerbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerbutton.setText("Enroll Now!");
        registerbutton.addActionListener(this::registerbuttonActionPerformed);
        getContentPane().add(registerbutton);
        registerbutton.setBounds(880, 260, 220, 60);

        adminbuttton.setBackground(new java.awt.Color(255, 255, 204));
        adminbuttton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adminbuttton.setText("Admin");
        adminbuttton.addActionListener(this::adminbutttonActionPerformed);
        getContentPane().add(adminbuttton);
        adminbuttton.setBounds(30, 140, 90, 23);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        jLabel10.setText("Easily Register and submit your Enrollment Information.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(650, 330, 660, 37);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Contact Us!");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 660, 131, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Address: Panapaan III,Emilio Aguinaldo Highway, Bacoor, 4102, Cavite");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 720, 427, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mobile Number: 0916 345 1302");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 750, 199, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Email: schoolbacoorbranch@sc.edu.ph");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 780, 232, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Mon-Fri: 8:00am to 6:00pm");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1160, 720, 171, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Office Hours: ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1160, 660, 158, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Adobe Express - file (3).png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(810, 400, 350, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminbutttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbutttonActionPerformed
        adminlogin admin = new adminlogin();
    admin.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_adminbutttonActionPerformed

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        enrollment enroll = new enrollment();
    enroll.setVisible(true);
    this.setVisible(false);
    
    }//GEN-LAST:event_registerbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminbuttton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registerbutton;
    // End of variables declaration//GEN-END:variables
}


