
import javax.swing.JFrame;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import javax.swing.*;
import java.awt.event.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rikiel
 */
public class adminform extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminform.class.getName());
    
    private java.util.Map<String, java.util.Map<String, java.util.List<String>>> strandSections = new java.util.HashMap<>();

    

    /**
     * Creates new form adminform
     */
    public adminform() {
    initComponents();
    setExtendedState(JFrame.MAXIMIZED_BOTH);

    createSectionsFileIfNotExists();
    loadSectionsFromCSV();

    // ✅ ADD SECTION COLUMN BEFORE loading registrations
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    boolean hasSection = false;
    
    jTable1.setDefaultEditor(Object.class, null);




    // ✅ NOW load table (IMPORTANT: after adding column)
    loadRegistrations();

    // ---------- SETUP COMBO BOXES ----------


    if (strandSections.isEmpty()) {
        strandSections.put("ICT", new java.util.HashMap<>());
        strandSections.get("ICT").put("Grade 11",
            new java.util.ArrayList<>(java.util.Arrays.asList("A", "B")));

        strandSections.put("ABM", new java.util.HashMap<>());
        strandSections.get("ABM").put("Grade 11",
            new java.util.ArrayList<>(java.util.Arrays.asList("A")));

        strandSections.put("HUMSS", new java.util.HashMap<>());
        strandSections.get("HUMSS").put("Grade 11",
            new java.util.ArrayList<>(java.util.Arrays.asList("A")));

        saveSectionsToCSV();
    }

    

    // ---------- TABLE SETTINGS ----------

    TableRowSorter<TableModel> sorter =
        new TableRowSorter<>(jTable1.getModel());
    jTable1.setRowSorter(sorter);

    searchField.addKeyListener(new KeyAdapter() {
        @Override
        public void keyReleased(KeyEvent e) {
            String text = searchField.getText();
            if (text.trim().isEmpty()) {
                sorter.setRowFilter(null);
            } else {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
            }
        }
    });

    jTable1.setRowHeight(28);
    jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14));
    jTable1.getTableHeader().setFont(
        new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14)
    );

}

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        Deletebutton = new javax.swing.JButton();
        Editbutton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Admin Menu");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school logo1.png"))); // NOI18N

        backbutton.setBackground(new java.awt.Color(255, 102, 102));
        backbutton.setText("Back");
        backbutton.addActionListener(this::backbuttonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(637, 637, 637)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 627, Short.MAX_VALUE)
                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Deletebutton.setBackground(new java.awt.Color(255, 102, 102));
        Deletebutton.setText("Delete");
        Deletebutton.addActionListener(this::DeletebuttonActionPerformed);

        Editbutton.setBackground(new java.awt.Color(102, 153, 255));
        Editbutton.setText("Edit");
        Editbutton.addActionListener(this::EditbuttonActionPerformed);

        searchField.addActionListener(this::searchFieldActionPerformed);

        jLabel3.setText("Search Bar:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student No", "Registration No", "Name", "Birth", "Nationality", "Email", "Address", "Phone", "Gender", "Strand", "Grade", "Guardian Name", "Guardian Contact", "Relationship", "Disability", "Disability Details"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane2.addTab("Student Application List", jScrollPane1);

        jTabbedPane1.addTab("Registrations", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(Deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(Editbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1817, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Deletebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        main mainWindow = new main();  // create a new main window
        mainWindow.setVisible(true);   // show main
        this.dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void DeletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebuttonActionPerformed
        
            int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Please select a row to delete."
        );
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete this record?",
        "Confirm Delete",
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (confirm != javax.swing.JOptionPane.YES_OPTION) {
        return;
    }

    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();

    model.removeRow(selectedRow);

    saveTableToCSV();
    }//GEN-LAST:event_DeletebuttonActionPerformed

    private void EditbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbuttonActionPerformed
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a row to edit.");
        return;
    }

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Get current values
    String name = model.getValueAt(selectedRow, 2).toString();
    String birth = model.getValueAt(selectedRow, 3).toString();
    String nationality = model.getValueAt(selectedRow, 4).toString();
    String email = model.getValueAt(selectedRow, 5).toString();
    String address = model.getValueAt(selectedRow, 6).toString();
    String phone = model.getValueAt(selectedRow, 7).toString();
    String gender = model.getValueAt(selectedRow, 8).toString();
    String strand = model.getValueAt(selectedRow, 9).toString();
    String grade = model.getValueAt(selectedRow, 10).toString();
    String guardianName = model.getValueAt(selectedRow, 11).toString();
    String guardianContact = model.getValueAt(selectedRow, 12).toString();
    String relationship = model.getValueAt(selectedRow, 13).toString();
    String disability = model.getValueAt(selectedRow, 14).toString();
    String disabilityDetails = model.getValueAt(selectedRow, 15).toString();
    // Section column may not exist yet
    String section = "";

    // Input fields
    JTextField nameField = new JTextField(name);
    JTextField birthField = new JTextField(birth);
    JTextField nationalityField = new JTextField(nationality);
    JTextField emailField = new JTextField(email);
    JTextField addressField = new JTextField(address);
    JTextField phoneField = new JTextField(phone);
    JComboBox<String> genderBox = new JComboBox<>(new String[]{"Male", "Female"});
    genderBox.setSelectedItem(gender);
    JComboBox<String> strandBox = new JComboBox<>(strandSections.keySet().toArray(new String[0]));
    strandBox.setSelectedItem(strand);
    JComboBox<String> gradeBox = new JComboBox<>(new String[]{"Grade 11", "Grade 12"});
    gradeBox.setSelectedItem(grade);
    JTextField guardianNameField = new JTextField(guardianName);
    JTextField guardianContactField = new JTextField(guardianContact);
    JTextField relationshipField = new JTextField(relationship);

    JComboBox<String> disabilityBox = new JComboBox<>(new String[]{"No", "Yes"});
    disabilityBox.setSelectedItem(disability);

JTextField disabilityDetailsField = new JTextField(disabilityDetails);


    Object[] message = {
        "Full Name:", nameField,
        "Birth (MM/DD/YYYY):", birthField,
        "Nationality:", nationalityField,
        "Email:", emailField,
        "Address:", addressField,
        "Phone:", phoneField,
        "Gender:", genderBox,
        "Strand:", strandBox,
        "Grade:", gradeBox,
        "Guardian Name:", guardianNameField,
        "Guardian Contact:", guardianContactField,
        "Relationship:", relationshipField,
        "Disability:", disabilityBox,
        "Disability Details:", disabilityDetailsField
    };

    int option = JOptionPane.showConfirmDialog(this, message, "Edit Registration", JOptionPane.OK_CANCEL_OPTION);

    if (option != JOptionPane.OK_OPTION) {
        return;
    }

    // Update table AFTER user confirms
    model.setValueAt(nameField.getText(), selectedRow, 2);
    model.setValueAt(birthField.getText(), selectedRow, 3);
    model.setValueAt(nationalityField.getText(), selectedRow, 4);
    model.setValueAt(emailField.getText(), selectedRow, 5);
    model.setValueAt(addressField.getText(), selectedRow, 6);
    model.setValueAt(phoneField.getText(), selectedRow, 7);
    model.setValueAt(genderBox.getSelectedItem().toString(), selectedRow, 8);
    model.setValueAt(strandBox.getSelectedItem().toString(), selectedRow, 9);
    model.setValueAt(gradeBox.getSelectedItem().toString(), selectedRow, 10);
    model.setValueAt(guardianNameField.getText(), selectedRow, 11);
    model.setValueAt(guardianContactField.getText(), selectedRow, 12);
    model.setValueAt(relationshipField.getText(), selectedRow, 13);
    model.setValueAt(disabilityBox.getSelectedItem().toString(), selectedRow, 14);
    model.setValueAt(disabilityDetailsField.getText(), selectedRow, 15);
    
    disabilityBox.addActionListener(e -> {
    boolean hasDisability = disabilityBox.getSelectedItem().equals("Yes");
    disabilityDetailsField.setEnabled(hasDisability);
});

    saveTableToCSV(); // Save everything after editing
    JOptionPane.showMessageDialog(this, "Record updated successfully.");
    }//GEN-LAST:event_EditbuttonActionPerformed


    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminform().setVisible(true));
    }
    
    private void loadRegistrations() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // clear table

    java.io.File file = new java.io.File("registrations.csv");
    if (!file.exists()) return;

    try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(file))) {
        String line;
        while ((line = br.readLine()) != null) {
            if (line.trim().isEmpty()) continue;

            String[] data = line.split(",", -1); // -1 keeps empty fields

            // Ensure exactly 12 columns (including Section)
            if (data.length < 16) {
                String[] fixed = new String[16];
                System.arraycopy(data, 0, fixed, 0, data.length);
                for (int i = data.length; i < 16; i++) fixed[i] = "";
                data = fixed;
            }

            // AUTO-ASSIGN SECTION if empty


            model.addRow(data);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error reading registrations: " + e.getMessage());
    }
}

    
    private void saveTableToCSV() {

    try (java.io.BufferedWriter bw =
            new java.io.BufferedWriter(new java.io.FileWriter("registrations.csv"))) {

        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            for (int j = 0; j < model.getColumnCount(); j++) {
                bw.write(model.getValueAt(i, j).toString());
                if (j < model.getColumnCount() - 1) {
                    bw.write(",");
                }
            }
            bw.newLine();
        }

    } catch (java.io.IOException e) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Error saving file: " + e.getMessage()
        );
    }
}

    
       
       
       
       

    private void createSectionsFileIfNotExists() {
    java.io.File file = new java.io.File("sections.csv");

    if (!file.exists()) {
        try (java.io.BufferedWriter bw =
                new java.io.BufferedWriter(new java.io.FileWriter(file))) {

            // Default sections with strand, grade, section
            bw.write("ICT,Grade 11,A"); bw.newLine();
            bw.write("ICT,Grade 11,B"); bw.newLine();
            bw.write("ABM,Grade 11,A"); bw.newLine();
            bw.write("HUMSS,Grade 11,A"); bw.newLine();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error creating sections file: " + e.getMessage());
        }
    }
}
    
    private void loadSectionsFromCSV() {
    strandSections.clear();

    try (java.io.BufferedReader br =
            new java.io.BufferedReader(new java.io.FileReader("sections.csv"))) {

        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(",");
            if (data.length != 3) continue; // strand, grade, section
            String strand = data[0];
            String grade = data[1];
            String section = data[2];

            // If the strand doesn't exist, create the inner map
            strandSections
                .computeIfAbsent(strand, k -> new java.util.HashMap<>())
                .computeIfAbsent(grade, k -> new java.util.ArrayList<>())
                .add(section);
        }

    } catch (Exception e) {
        System.out.println("Error loading sections: " + e.getMessage());
    }
}
    
    private void saveSectionsToCSV() {
    try (java.io.BufferedWriter bw = new java.io.BufferedWriter(new java.io.FileWriter("sections.csv"))) {
        for (String strand : strandSections.keySet()) {
            for (String grade : strandSections.get(strand).keySet()) {
                for (String section : strandSections.get(strand).get(grade)) {
                    bw.write(strand + "," + grade + "," + section);
                    bw.newLine();
                }
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error saving sections: " + e.getMessage());
    }
}
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deletebutton;
    private javax.swing.JButton Editbutton;
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
