
import javax.swing.JFrame;
import com.toedter.calendar.JDateChooser;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rikiel
 */
public class enrollment extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(enrollment.class.getName());

    /**
     * Creates new form enrollment
     */
    public enrollment() {
        initComponents();
        
        DisabilityBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"No", "Yes"}));
DisabilityDetailsField.setEnabled(false);

DisabilityBox.addActionListener(e -> {
    boolean hasDisability = DisabilityBox.getSelectedItem().equals("Yes");
    DisabilityDetailsField.setEnabled(hasDisability);
    if (!hasDisability) DisabilityDetailsField.setText("");
});
        
        
        
        
        


        
        
        jDateChooser1.setDateFormatString("MM/dd/yyyy");
        jTextField1.setText("09XXXXXXXXX");

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        MaleBox.addActionListener(e -> {
    if (MaleBox.isSelected()) {
        FemaleBox.setSelected(false);
    }
});

FemaleBox.addActionListener(e -> {
    if (FemaleBox.isSelected()) {
        MaleBox.setSelected(false);
    }
});

// --- STRAND CHECKBOXES ---
ICTbox.addActionListener(e -> {
    if (ICTbox.isSelected()) {
        ABMbox.setSelected(false);
        HUMSSbox.setSelected(false);
    }
});

ABMbox.addActionListener(e -> {
    if (ABMbox.isSelected()) {
        ICTbox.setSelected(false);
        HUMSSbox.setSelected(false);
    }
});

HUMSSbox.addActionListener(e -> {
    if (HUMSSbox.isSelected()) {
        ICTbox.setSelected(false);
        ABMbox.setSelected(false);
    }
});

// --- GRADE LEVEL CHECKBOXES ---
jCheckBox1.addActionListener(e -> {
    if (jCheckBox1.isSelected()) {
        jCheckBox2.setSelected(false);
    }
});

jCheckBox2.addActionListener(e -> {
    if (jCheckBox2.isSelected()) {
        jCheckBox1.setSelected(false);
    }
});


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backbutton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NationalityField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AddressField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        MaleBox = new javax.swing.JCheckBox();
        FemaleBox = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ICTbox = new javax.swing.JCheckBox();
        HUMSSbox = new javax.swing.JCheckBox();
        ABMbox = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        GuardianContactField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        RelationshipField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        DisabilityBox = new javax.swing.JComboBox<>();
        DisabilityDetailsField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        GuardianNameField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Enrollment Form");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/school logo1.png"))); // NOI18N

        backbutton.setBackground(new java.awt.Color(255, 51, 51));
        backbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbutton.setText("Back");
        backbutton.addActionListener(this::backbuttonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(627, 627, 627)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Guardian Information*");

        NameField.addActionListener(this::NameFieldActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Full Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Date of Birth:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Nationality/Citizenship");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Contact Information*");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Email:");

        EmailField.addActionListener(this::EmailFieldActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Address:");

        AddressField.addActionListener(this::AddressFieldActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Phone Number:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Gender:");

        MaleBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MaleBox.setText("Male");

        FemaleBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FemaleBox.setText("Female");
        FemaleBox.addActionListener(this::FemaleBoxActionPerformed);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Academic Information*");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Strand:");

        ICTbox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ICTbox.setText("ICT");

        HUMSSbox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        HUMSSbox.setText("HUMSS");
        HUMSSbox.addActionListener(this::HUMSSboxActionPerformed);

        ABMbox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ABMbox.setText("ABM");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Grade Level:");

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox1.setText("Enrolling for Grade 11");
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);

        jCheckBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox2.setText("Enrolling for Grade 12");

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Personal Information*");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Guardian Name");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Guardian Contact:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Relationship");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Disability:");

        DisabilityBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Disability Details");

        GuardianNameField1.addActionListener(this::GuardianNameField1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(NationalityField)
                        .addComponent(NameField, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MaleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FemaleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DisabilityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DisabilityDetailsField, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GuardianNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(GuardianContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(RelationshipField, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EmailField)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(AddressField)
                                .addComponent(jLabel8)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ABMbox)
                                    .addComponent(HUMSSbox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(ICTbox))
                                        .addGap(130, 130, 130)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jCheckBox2)
                                                    .addComponent(jCheckBox1)))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(360, 360, 360)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1360, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NationalityField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FemaleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DisabilityBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DisabilityDetailsField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ICTbox)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ABMbox)
                            .addComponent(jCheckBox2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HUMSSbox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GuardianNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GuardianContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RelationshipField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(160, 160, 160)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(942, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        main mainWindow = new main();  // create a new main window
            mainWindow.setVisible(true);   // show main
            this.dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void AddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressFieldActionPerformed

    private void FemaleBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleBoxActionPerformed

    private void HUMSSboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HUMSSboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HUMSSboxActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    // --- INPUT VALIDATION ---
    if (NameField.getText().trim().isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Please enter your full name.");
    return;
}
    if (jDateChooser1.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Please select your date of birth.");
    return;
}
    
    
    

    if (NationalityField.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter your nationality.");
        return;
    }

    if (EmailField.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter your email.");
        return;
    }

    if (!EmailField.getText().matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid email address.");
        return;
    }

    if (AddressField.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter your address.");
        return;
    }

    if (jTextField1.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter your phone number.");
        return;
    }

    if (!jTextField1.getText().matches("\\d+")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Phone number must contain digits only.");
        return;
    }

    if (!MaleBox.isSelected() && !FemaleBox.isSelected()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select your gender.");
        return;
    }

    if (!ICTbox.isSelected() && !ABMbox.isSelected() && !HUMSSbox.isSelected()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select your strand.");
        return;
    }

    if (!jCheckBox1.isSelected() && !jCheckBox2.isSelected()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select your grade level.");
        return;
    }



if (GuardianContactField.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter guardian contact.");
    return;
}

if (!GuardianContactField.getText().matches("\\d+")) {
    JOptionPane.showMessageDialog(this, "Guardian contact must contain digits only.");
    return;
}

if (RelationshipField.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter relationship.");
    return;
}

if (DisabilityBox.getSelectedItem().equals("Yes") &&
    DisabilityDetailsField.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter disability details.");
    return;
}

        
    String name = NameField.getText();
    java.util.Date selectedDate = jDateChooser1.getDate();

java.text.SimpleDateFormat sdf =
        new java.text.SimpleDateFormat("MM/dd/yyyy");

String birth = sdf.format(selectedDate);
    String nationality = NationalityField.getText();
    String email = EmailField.getText();
    String address = AddressField.getText();
    String phone = jTextField1.getText();

    // Gender
    String gender = "";
    if (MaleBox.isSelected()) gender = "Male";
    else if (FemaleBox.isSelected()) gender = "Female";

    // Strand
    String strand = "";
    if (ICTbox.isSelected()) strand = "ICT";
    else if (ABMbox.isSelected()) strand = "ABM";
    else if (HUMSSbox.isSelected()) strand = "HUMSS";
    
String guardianName = GuardianNameField1.getText();
String guardianContact = GuardianContactField.getText();
String relationship = RelationshipField.getText();
String disability = DisabilityBox.getSelectedItem().toString();
String disabilityDetails = DisabilityDetailsField.getText();

    // Grade
    String grade = "";
    if (jCheckBox1.isSelected()) grade = "Grade 11";
    else if (jCheckBox2.isSelected()) grade = "Grade 12";

    // Combine data as CSV line
    int studentNo;
String registrationNo;

// Grade 11 → always new student number
if (grade.equals("Grade 11")) {

    studentNo = getNextStudentNumber();
    registrationNo = generateRegistrationNumber(studentNo);

// Grade 12 → ask if former student
} else {

    int choice = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Did you study Grade 11 in this school?",
        "Grade 12 Enrollment",
        javax.swing.JOptionPane.YES_NO_OPTION
    );

    // Former student
    if (choice == javax.swing.JOptionPane.YES_OPTION) {

        String input = javax.swing.JOptionPane.showInputDialog(
            this,
            "Enter your Student Number:"
        );

        if (input == null || input.isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Student number is required."
            );
            return;
        }

        try {
            studentNo = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Invalid student number."
            );
            return;
        }

        if (!studentNumberMatchesName(studentNo, name)) {
    javax.swing.JOptionPane.showMessageDialog(
        this,
        "Student number does not match the name.\nPlease check your entry or contact the registrar."
    );
    return;
}

        registrationNo = generateRegistrationNumber(studentNo);

    // Transfer student
    } else {

        studentNo = getNextStudentNumber();
        registrationNo = generateRegistrationNumber(studentNo);
    }
}


String line = String.join(",",
    String.valueOf(studentNo),
    registrationNo,
    name,
    birth,
    nationality,
    email,
    address,
    phone,
    gender,
    strand,
    grade,
    guardianName,
    guardianContact,
    relationship,
    disability,

    disabilityDetails
        
);
    try {
        java.io.FileWriter fw = new java.io.FileWriter("registrations.csv", true); // append mode
        java.io.BufferedWriter bw = new java.io.BufferedWriter(fw);
        bw.write(line);
        bw.newLine();
        bw.close();
    } catch (java.io.IOException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error saving registration: " + e.getMessage());
        return;
    }

    // Show confirmation popup
    javax.swing.JOptionPane.showMessageDialog(
        this,
        "You have successfully registered!",
        "Registration Complete",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );

    // Go back to main.java
    main mainWindow = new main();
    mainWindow.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GuardianNameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardianNameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardianNameField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new enrollment().setVisible(true));
    }

    
    private int getNextStudentNumber() {
    java.io.File file = new java.io.File("registrations.csv");
    int max = 259; // so first becomes 260

    if (!file.exists()) {
        return 260;
    }

    try (java.io.BufferedReader br =
            new java.io.BufferedReader(new java.io.FileReader(file))) {

        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(",", -1);
            if (data.length >= 1) {
                try {
                    int num = Integer.parseInt(data[0]);
                    if (num > max) max = num;
                } catch (NumberFormatException ignored) {}
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    return max + 1;
}

// Registration number is tied to student number
private String generateRegistrationNumber(int studentNo) {
    return "REG-" + studentNo;
}

private boolean studentNumberExists(int studentNo) {
    java.io.File file = new java.io.File("registrations.csv");

    if (!file.exists()) return false;

    try (java.io.BufferedReader br =
            new java.io.BufferedReader(new java.io.FileReader(file))) {

        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(",", -1);
            if (data.length >= 1) {
                try {
                    if (Integer.parseInt(data[0]) == studentNo) {
                        return true;
                    }
                } catch (NumberFormatException ignored) {}
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    return false;
}

private boolean studentNumberMatchesName(int studentNo, String name) {
    java.io.File file = new java.io.File("registrations.csv");

    if (!file.exists()) return false;

    try (java.io.BufferedReader br =
            new java.io.BufferedReader(new java.io.FileReader(file))) {

        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(",", -1);

            // CSV format:
            // 0 studentNo, 1 regNo, 2 name
            if (data.length >= 3) {
                try {
                    int fileStudentNo = Integer.parseInt(data[0]);
                    String fileName = data[2].trim();

                    if (fileStudentNo == studentNo &&
                        fileName.equalsIgnoreCase(name.trim())) {
                        return true;
                    }
                } catch (NumberFormatException ignored) {}
            }
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    return false;
}

    
    
    
    


    
        
        
        
       
        



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ABMbox;
    private javax.swing.JTextField AddressField;
    private javax.swing.JComboBox<String> DisabilityBox;
    private javax.swing.JTextField DisabilityDetailsField;
    private javax.swing.JTextField EmailField;
    private javax.swing.JCheckBox FemaleBox;
    private javax.swing.JTextField GuardianContactField;
    private javax.swing.JTextField GuardianNameField1;
    private javax.swing.JCheckBox HUMSSbox;
    private javax.swing.JCheckBox ICTbox;
    private javax.swing.JCheckBox MaleBox;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextField NationalityField;
    private javax.swing.JTextField RelationshipField;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
